### ISSUE TITLE
https error on FIRST links

### ISSUE THREAD

**Issue by patkub** [FRC1991/frc1991.github.io#1]
It looks like https://firstinspires.org/ doesn't work directly, but non-https redirects to https version.
https://nefirst.org/ also doesn't work directly and doesn't redirect to https version. So change both to non-https.

**Comment by Nexuist** [comment]
Hi,

Thank you for pointing this out. The fixes have been pushed with commit https://github.com/FRC1991/frc1991.github.io/commit/176acbb29977e46abbf83235524f58d113484c40.
